spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 3

  jpa:
    show-sql: true
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: embedded


server:
  port: ${SERVER_PORT}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
