server:
  port: 4000
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trumpet.db.elephantsql.com/dvbxgjdp
    username: dvbxgjdp
    password: FiQRi2a7m-DkodYjvR9soTpBibKlwOst
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
