spring:
  datasource:
    url: jdbc:postgresql://<DB_URL>:5432/<DB_NAME>
    username: <USERNAME>
    password: <PASSWORD>
    hikari:
      maximum-pool-size: 3

  jpa:
    show-sql: true
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: embedded


server:
  port: 4000
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
