FROM openjdk:21-jdk-slim AS build

WORKDIR /app
COPY . .
RUN ./gradlew bootJar

FROM openjdk:21-jdk-slim
WORKDIR /app
COPY --from=build /app/build/libs/cinema-0.0.1-SNAPSHOT.jar .
EXPOSE 4000
CMD ["java", "-jar", "cinema-0.0.1-SNAPSHOT.jar"]
