FROM eclipse-temurin:17

WORKDIR /app

COPY java.docker.day.1-0.0.1-SNAPSHOT.jar /app/java.docker.day.1-0.0.1-SNAPSHOT.jar

EXPOSE 4000

ENTRYPOINT ["java", "-jar", "java.docker.day.1-0.0.1-SNAPSHOT.jar"]