openapi: 3.0.3
info:
  title: Java API Exercise - Core Criteria
  description: API for managing student data in a bootcamp
  version: 0.2.2

servers:
  - url: http://localhost:4000
tags:
  - name: students
paths:
  /students:
    get:
      summary: Get all students
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                students:
                  - id: 1
                    firstName: John
                    lastName: Doe
                    dob: '1990-01-01'
                    courseTitle: Web Development
                    startDate: '2024-02-01'
                    averageGrade: 85.5
                  - id: 2
                    firstName: Jane
                    lastName: Smith
                    dob: '1992-05-15'
                    courseTitle: Data Science
                    startDate: '2024-02-15'
                    averageGrade: 92.0
    post:
      summary: Add a new student
      requestBody:
        required: true
        content:
          application/json:
            example:
              firstName: John
              lastName: Doe
              dob: '1990-01-01'
              courseTitle: Web Development
              startDate: '2024-02-01'
              averageGrade: 85.5
      responses:
        '201':
          description: Student added successfully
          content:
            application/json:
              example:
                message: Student added successfully
                student:
                  id: 3
                  firstName: John
                  lastName: Doe
                  dob: '1990-01-01'
                  courseTitle: Web Development
                  startDate: '2024-02-01'
                  averageGrade: 85.5

  /students/{studentId}:
    parameters:
      - name: studentId
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Get a specific student by ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                student:
                  id: 1
                  firstName: John
                  lastName: Doe
                  dob: '1990-01-01'
                  courseTitle: Web Development
                  startDate: '2024-02-01'
                  averageGrade: 85.5
    put:
      summary: Update an existing student by ID
      requestBody:
        required: true
        content:
          application/json:
            example:
              firstName: UpdatedJohn
              lastName: UpdatedDoe
              dob: '1990-01-01'
              courseTitle: Web Development
              startDate: '2024-02-01'
              averageGrade: 90.0
      responses:
        '200':
          description: Student updated successfully
          content:
            application/json:
              example:
                message: Student updated successfully
                student:
                  id: 1
                  firstName: UpdatedJohn
                  lastName: UpdatedDoe
                  dob: '1990-01-01'
                  courseTitle: Web Development
                  startDate: '2024-02-01'
                  averageGrade: 90.0
    delete:
      summary: Delete a student by ID
      responses:
        '200':
          description: Student deleted successfully
