openapi: 3.0.3
info:
  title: Java API Exercise - Core Criteria
  description: |
    Version: 0.2.2
  version: 0.2.2

servers:
  - url: http://localhost:4000

tags:
  - name: students, courses

paths:
  /courses:
    post:
      tags:
        - courses
      summary: course POST route
      description: Adds course
      operationId: addCourse
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCourse'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
    get:
      tags:
        - courses
      summary: Course GET route
      description: Get all courses
      operationId: getAllCourses
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllCourses'

  /courses/{id}:
    put:
      tags:
        - courses
      summary: Course PUT route
      description: Update course
      operationId: updateCourse
      parameters:
        - name: id
          in: path
          description: The ID of the course to update
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCourse'
      responses:
        '201':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
    delete:
      tags:
        - courses
      summary: Course DELETE route
      description: Deletes course
      operationId: deleteCourse
      parameters:
        - name: id
          in: path
          description: The ID of the course to delete
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
  /students:
    post:
      tags:
        - students
      summary: Student POST route
      description: Adds student
      operationId: addStudent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStudent'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
    get:
      tags:
        - students
      summary: Student GET route
      description: Get all students
      operationId: getAllStudents
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllStudents'

  /students/{id}:
    put:
      tags:
        - students
      summary: Student PUT route
      description: Update student
      operationId: updateStudent
      parameters:
        - name: id
          in: path
          description: The ID of the student to update
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStudent'
      responses:
        '201':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
    delete:
      tags:
        - students
      summary: Student DELETE route
      description: Deletes student
      operationId: deleteStudent
      parameters:
        - name: id
          in: path
          description: The ID of the student to delete
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'

components:
  schemas:
    CreateCourse:
      type: object
      required: [ title, startDate ]
      properties:
        title:
          type: string
          example: "Course"
        startDate:
          type: string
          example: "04.04.03"
    Course:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "Course"
        startDate:
          type: string
          example: "03.03.03"
    AllCourses:
      type: array
      items:
        $ref: '#/components/schemas/Course'

    CreateStudent:
      type: object
      required: [firstName, lastName, dob, courseTitle, courseStartDate]
      properties:
        firstName:
          type: string
          example: "Jared"
        lastName:
          type: string
          example: "Leto"
        dob:
          type: string
          example: "08.05.00"
        courseTitle:
          type: string
          example: "Technology"
        courseStartDate:
          type: string
          example: "08.05.24"
    Student:
      type: object
      properties:
        id:
          type: integer
          example: 1
        firstName:
          type: string
          example: "Jared"
        lastName:
          type: string
          example: "Leto"
        dob:
          type: string
          example: "08.05.00"
        courseTitle:
          type: string
          example: "Technology"
        courseStartDate:
          type: string
          example: "08.05.24"
    AllStudents:
      type: array
      items:
        $ref: '#/components/schemas/Student'
